### ISSUE TITLE
Just a thought

### ISSUE THREAD

**Issue by Benomrans** [lovasoa/ZIF#3]
- This wonderful format didn't take its well deserved place, just because of not being introduced properly to the world.
- there are only two places offering the converters to zif format: zoomify.com with min. license price of 180Usd. and objectivepathology.com with a price of 3000Usd (yes 3k). and it is not usable only with zoomify image viewer.
- what if someone created a licenseable relatively much cheaper converter, and implement the zif format with Openseadragon and maybe Openlayers to create the demand. wouldn't that be a good idea making some income?

(Just a thought after reading this openseadragon/issues/944 for such an issue hanging for 9 years and no one came with a solution) :)

**Comment by KempWatson** [comment]
Thanks for the shout-out!

We made the Zoomify ZIF converter as a cheaper alternative to our ObjectiveConvert, as ObjectiveConvert does much more for that $3K (digital pathology file formats), and as a more tractable format than the previous Zoomify PFF format. As Zoomify is unfortunately no longer operating, we could certainly offer a ZIF converter along with some other tools very affordably. Could also have standard DZI and Zoomify folders too for backwards compatibiity.

**Comment by Benomrans** [comment]
@KempWatson 
Thank you so much for your kind comment.
Can't express enough my admiration of your wonderful zif format, it's perfect in every aspect regarding zoomable imaging.
The idea is that zif file format should be implemented within Openseadragon directly, not as an external plug-in, which would be a huge service to the users in solving different problems of tiles handling especially the back-end storage. At the same time a zif files converter to be offered, just zif format and zoomify tiles folders, with the converting options especially the jpeg compression quality.
That discussion at openseadragon repository clearly shows that no one was able to reach such approach. I hope someday it will be done.
Many thanks.

**Comment by lovasoa** [comment]
Hey ! I know I'm late, but I just added a clean rust ZIF reader / writer library to this repo: https://github.com/lovasoa/ZIF/tree/master/zif-rs

**Comment by lovasoa** [comment]
I also wrote a new tiff-independant specification for the format: https://github.com/lovasoa/ZIF/blob/master/SPECIFICATION.md

(it's 10x smaller than the [full tiff spec](https://github.com/lovasoa/ZIF/blob/master/tiff6.md))

**Comment by Benomrans** [comment]
Well done. Great work as always. Thank you so much.

**Comment by KempWatson** [comment]
Given that the TIFF specification is hosted officially at https://zif.photo,
and has been since the format's inception,
I think we ahould be careful about calling this "the specification". No
matter the accuracy, it is a reverse-engineering.
In fact "This document fully specifies the ZIF file format" could be
considered appropriative, although I doubt that was the intent,
as the author has been in touch with me recently and has been doing some
great work with the format.

That said, I like the format of the document, and it adds a lot of value
for implementors.
Might I suggest that we work to merge the documents, and then fork the
merged specification back to lovesoa/ZIF?

I'd love to see SDKs for ZIF in various languages and am happy to support
efforts where I can.

W. Kemp Watson, Managing Director
Objective Pathology Services Limited
Toronto, Canada

(creator of ZIF format)

**Comment by lovasoa** [comment]
@KempWatson Thank you for clarifying ! I’m sorry. I overstepped in calling this "the specification". My intention was to make the format easier to understand and implement, not to appropriate or replace the official ZIF specification or its authorship.

I’d be very happy to work with you on merging the documents and aligning this repository with the official specification at zif.photo. Once we have a merged version, I can fork or mirror it back here as you suggested.

**Comment by lovasoa** [comment]
I added the following to  https://github.com/lovasoa/ZIF/blob/master/SPECIFICATION.md : 

> ZIF was created by W. Kemp Watson at Objective Pathology Services Ltd. This document is an implementation-oriented description of the format, reconstructed from the official ZIF documentation, the [TIFF](https://github.com/lovasoa/ZIF/blob/master/tiff6.md) and [BigTIFF](https://github.com/lovasoa/ZIF/blob/master/bigtiff.md) specifications. It is intended to help implementors, not to replace the official specification at https://zif.photo/. If these documents conflict, the official documentation is authoritative (but please [open an issue](https://github.com/lovasoa/ZIF/issues)).

**Comment by KempWatson** [comment]
Thanks Ophir, and that wording sounds good to me. We can take the document
merging offline and repost back here when done.
It's overdue anyway :-)

W. Kemp Watson, Managing Director
Objective Pathology Services Limited
Toronto, Canada
